site_name: 未央学习

repo_url: https://github.com/WeYoung-learn./WeYoung-learn.github.io
repo_name: WeYoung-learn

theme:
  name: material
  custom_dir: overrides
  language: zh
  icon:
    logo: material/file-document
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation
    - navigation.top

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - glightbox
  - search

extra:
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/pdfjs-dist@3.10.111/build/pdf.min.js

nav:
  - 首页:
      - 欢迎来到未央学习: "index.md"
      - 读者须知: "reader.md"
      - 加入我们！: "author.md"
  - 课程指引:
      - 介绍: "courses/index.md"
      - 必修课:
          - 微积分: "courses/basic/calculus/index.md"
          - 线性代数: "courses/basic/linear_algebra/index.md"
          - 程序设计基础: "courses/basic/programming/index.md"
          - 基础物理学: "courses/basic/fundamental_physics/index.md"
          - 离散数学: "courses/basic/discrete_mathematics/index.md"
          - 概率论: "courses/basic/probability/index.md"
          - 工程图学基础: "courses/basic/fundamentals_of_engineering_graphics/index.md"
          - 复变函数: "courses/basic/complex_func/index.md"
          - 数理方程: "courses/basic/mathematical_physics_equations/index.md"
      - 专业课:
          - 储能技术: "courses/professional/energy_storage_technology/index.md"
          - 常微分方程: "courses/professional/ordinary_differential_equation/index.md"
          - 动力建模与仿真: "courses/professional/dynamic_modeling_and_simulation/index.md"
          - 工程热力学: "courses/professional/engineering_thermodynamics/index.md"
          - 工程经济学: "courses/professional/engineering_economics/index.md"
          - 高等线性代数选讲: "courses/professional/advanced_algebra_selected/index.md"
          - 经济学原理: "courses/professional/principles_of_economics/index.md"
          - 统计力学: "courses/professional/statistical_mechanics/index.md"
  - 技能培训:
      - 介绍: "skills/index.md"
      - mkdocs：搭建一个属于你的小网站: "skills/mkdocs.md"
      - Markdown：无纸化学习必备: "skills/markdown.md"
      - EndNote： 你的宝藏文献管理工具: "skills/endnote.md"
      - MATLAB 讲座: "skills/matlab.md"
      - LaTeX 讲座: "skills/latex.md"
      - R 语言使用指南: "skills/R.md"
      - JetBrains 学生认证申请指北: "skills/jetbrains.md"
  - 资源链接:
      - 介绍: "resources/index.md"
      - 乐学资源: "resources/lexue/index.md"
  - 未央活动:
      - 介绍: "activities/index.md"
